"use client";

import { useState, useTransition } from "react";
import { TbCheck, TbPackage, TbPaperclip, TbPlus, TbTruckDelivery, TbX } from "react-icons/tb";
import { toast } from "sonner";
import { createEngineerMaterialRequestAction, markMaterialReceivedAction } from "@/actions/engineer";
import EngineerPageHeader from "@/features/engineer/components/EngineerPageHeader";
import EngineerPreviewBanner from "@/features/engineer/components/EngineerPreviewBanner";
import type { EngineerMaterialRequest, EngineerProject } from "@/features/engineer/types";
import { formatEngineerDate, humanizeEngineerStatus } from "@/features/engineer/utils/engineerDashboard";

const workflow = ["pending", "assigned", "ordered", "delivered", "received"];
const field = "h-10 w-full rounded-[6px] border border-[#d9e2dc] bg-white px-3 text-sm outline-none focus:border-[#087332]";

function RequestDialog({ projects, preview, onMockSubmit, onClose }: { projects: EngineerProject[]; preview: boolean; onMockSubmit: (data: FormData) => void; onClose: () => void }) {
  const [pending, startTransition] = useTransition();
  const submit = (form: HTMLFormElement) => startTransition(async () => {
    try {
      const data = new FormData(form);
      if (preview) onMockSubmit(data); else await createEngineerMaterialRequestAction(data);
      toast.success("Material request submitted for CEO approval."); onClose();
    } catch (error) { toast.error(error instanceof Error ? error.message : "Could not submit request."); }
  });
  return <div className="fixed inset-0 z-[80] grid place-items-center bg-[#111827]/35 p-3"><button className="absolute inset-0" onClick={onClose} aria-label="Close request form" /><form className="relative z-10 w-full max-w-[650px] rounded-[8px] border border-[#dbe4de] bg-white shadow-[0_24px_70px_rgba(15,45,26,0.18)]" onSubmit={(event) => { event.preventDefault(); submit(event.currentTarget); }}><div className="flex items-center justify-between border-b border-[#e1e7e3] p-5"><div><h2 className="text-lg font-semibold">New material request</h2><p className="mt-1 text-xs text-[#76808a]">Send a complete site requirement for approval.</p></div><button type="button" onClick={onClose}><TbX size={20} /></button></div><div className="grid gap-4 p-5 sm:grid-cols-2"><label className="grid gap-1.5 text-xs font-semibold sm:col-span-2">Project<select name="projectId" required className={field}><option value="">Select project</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label><label className="grid gap-1.5 text-xs font-semibold">Material<input name="materialName" required className={field} /></label><label className="grid gap-1.5 text-xs font-semibold">Quantity / unit<span className="flex gap-2"><input name="quantity" type="number" min="0.01" step="0.01" required className={field} /><input name="unit" required placeholder="bags, pcs, m³" className={field} /></span></label><label className="grid gap-1.5 text-xs font-semibold">Estimated cost<input name="estimatedCost" type="number" min="0" step="0.01" className={field} /></label><label className="grid gap-1.5 text-xs font-semibold">Supplier (optional)<input name="supplier" className={field} /></label><label className="grid gap-1.5 text-xs font-semibold">Urgency<select name="priority" defaultValue="medium" className={field}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="urgent">Urgent</option></select></label><label className="grid gap-1.5 text-xs font-semibold">Needed by<input name="neededBy" type="date" required className={field} /></label><label className="grid gap-1.5 text-xs font-semibold sm:col-span-2">Reason<textarea name="reason" rows={3} required className={`${field} h-auto p-3`} /></label><label className="flex cursor-pointer items-center gap-2 rounded-[6px] border border-dashed border-[#b8cabe] p-4 text-xs font-semibold text-[#087332] sm:col-span-2"><TbPaperclip />Attach quotation, photo, or specification<input name="attachment" type="file" accept="image/*,application/pdf" className="sr-only" /></label></div><div className="flex justify-end border-t border-[#e1e7e3] p-4"><button disabled={pending || !projects.length} className="h-10 rounded-[6px] bg-[#087332] px-5 text-xs font-semibold text-white">{pending ? "Submitting…" : "Submit request"}</button></div></form></div>;
}

export default function EngineerMaterialRequestsPageClient({ projects, requests, preview = false }: { projects: EngineerProject[]; requests: EngineerMaterialRequest[]; preview?: boolean }) {
  const [open, setOpen] = useState(false); const [pending, startTransition] = useTransition(); const [visibleRequests, setVisibleRequests] = useState(requests);
  const addMockRequest = (data: FormData) => { const project = projects.find((item) => item.id === String(data.get("projectId"))); if (!project) return; setVisibleRequests((current) => [{ id: `mock-request-${Date.now()}`, project_id: project.id, material_name: String(data.get("materialName")), quantity: Number(data.get("quantity")), unit: String(data.get("unit")), estimated_cost: Number(data.get("estimatedCost")) || null, supplier: String(data.get("supplier") || "") || null, reason: String(data.get("reason")), priority: String(data.get("priority")) as EngineerMaterialRequest["priority"], needed_by: String(data.get("neededBy")), status: "pending", attachment_path: null, created_at: new Date().toISOString(), project: { id: project.id, name: project.name, site: project.site } }, ...current]); };
  const receive = (id: string) => startTransition(async () => { try { if (preview) setVisibleRequests((current) => current.map((item) => item.id === id ? { ...item, status: "received" } : item)); else await markMaterialReceivedAction(id); toast.success("Materials marked received on site."); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not update request."); } });
  return <div className="mx-auto max-w-[1420px] p-4 sm:p-7">{preview ? <EngineerPreviewBanner /> : null}<EngineerPageHeader title="Material Requests" description="Track every request from approval through site receipt." action={<button onClick={() => setOpen(true)} className="inline-flex h-10 items-center gap-2 rounded-[6px] bg-[#087332] px-4 text-xs font-semibold text-white"><TbPlus />New request</button>} /><section className="mt-6 overflow-hidden rounded-[7px] border border-[#d9e2dc] bg-white"><div className="hidden grid-cols-[minmax(220px,1.5fr)_120px_130px_minmax(360px,2fr)_110px] border-b border-[#e1e7e3] px-5 py-3 text-[9px] font-semibold uppercase tracking-[0.08em] text-[#77808a] lg:grid"><span>Request</span><span>Quantity</span><span>Estimated cost</span><span>Workflow</span><span>Action</span></div><div className="divide-y divide-[#e3e8e5]">{visibleRequests.map((request) => { const current = request.status === "approved" ? 1 : request.status === "partially_delivered" ? 3 : Math.max(0, workflow.indexOf(request.status)); return <article key={request.id} className="grid gap-4 px-5 py-4 lg:grid-cols-[minmax(220px,1.5fr)_120px_130px_minmax(360px,2fr)_110px] lg:items-center"><div className="flex gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-[#e9f4ec] text-[#087332]"><TbPackage /></span><div><h3 className="text-xs font-semibold">{request.material_name}</h3><p className="mt-1 text-[9px] text-[#747d86]">{request.project?.name} · Needed {formatEngineerDate(request.needed_by)}</p></div></div><p className="text-xs font-semibold">{request.quantity} {request.unit}</p><p className="text-xs">{request.estimated_cost ? `₱${request.estimated_cost.toLocaleString()}` : "—"}</p><div className="flex items-center">{workflow.map((step, index) => <div key={step} className="flex min-w-0 flex-1 items-center last:flex-none"><span title={humanizeEngineerStatus(step)} className={`grid h-6 w-6 shrink-0 place-items-center rounded-full border text-[9px] ${index <= current ? "border-[#087332] bg-[#087332] text-white" : "border-[#cbd5ce] bg-white text-[#87918a]"}`}>{index < current ? <TbCheck /> : index + 1}</span>{index < workflow.length - 1 ? <span className={`h-px flex-1 ${index < current ? "bg-[#087332]" : "bg-[#d3dcd6]"}`} /> : null}</div>)}</div><div>{request.status === "delivered" ? <button disabled={pending} onClick={() => receive(request.id)} className="inline-flex items-center gap-1 rounded-[5px] bg-[#087332] px-3 py-2 text-[9px] font-semibold text-white"><TbTruckDelivery />Receive</button> : <span className="text-[9px] font-semibold text-[#68717a]">{humanizeEngineerStatus(request.status)}</span>}</div></article>; })}</div>{!visibleRequests.length ? <p className="p-12 text-center text-sm text-[#7a838c]">No material requests yet.</p> : null}</section>{open ? <RequestDialog projects={projects} preview={preview} onMockSubmit={addMockRequest} onClose={() => setOpen(false)} /> : null}</div>;
}
