import fs from "node:fs";
import path from "node:path";

export function buildDemoSchemaRepair(root = process.cwd()) {
  const read = (name) => fs.readFileSync(path.join(root, "supabase", name), "utf8").replace(/^\uFEFF/, "");
  const projects = read("projects-schema.sql");
  const submissions = projects.match(/create table if not exists public\.project_progress_submissions\s*\([\s\S]*?\n\);/i)?.[0];
  const policies = projects.match(/drop policy if exists "progress submissions readable by project members"[\s\S]*?(?=create or replace function)/i)?.[0];
  if (!submissions || !policies) throw new Error("Could not locate project progress submission migration statements.");
  const sources = [
    ["repair-payroll-schema.sql", read("repair-payroll-schema.sql")],
    ["payroll-attendance-review.sql", read("payroll-attendance-review.sql")],
    ["projects-schema.sql (progress submissions only)", `${submissions}\ncreate index if not exists progress_submissions_project_idx on public.project_progress_submissions(project_id,submitted_at desc);\nalter table public.project_progress_submissions enable row level security;\n${policies}`],
    ["project-progress-updates.sql", read("project-progress-updates.sql")],
    ["gmea-08-project-status.sql", read("gmea-08-project-status.sql")],
  ];
  return [
    "-- Generated by npm run seed:prepare from the repository's migration files.",
    "-- Repairs the older schema reported by seed:data. Keeps existing records.",
    "-- Run this entire file in the SQL Editor of the same Supabase project as .env.local.",
    "begin;",
    ...sources.map(([name, sql]) => `\n-- Source: ${name}\n${sql.replace(/^\s*(begin|commit);\s*$/gim, "")}`),
    "notify pgrst, 'reload schema';",
    "commit;\n",
  ].join("\n");
}
