"use client";

import { useState, useTransition } from "react";
import { AlertTriangle, Camera, CheckCircle2, ClipboardList, HardHat, Send } from "lucide-react";
import { toast } from "sonner";
import { submitProgressUpdateAction, updateOperationsTaskStatusAction } from "@/actions/operations";
import type { OperationsProject } from "@/features/operations/types";
import { formatOperationsDate, taskCompletion } from "@/features/operations/utils/operationsFormatters";

export default function EngineerOperationsPageClient({ projects }: { projects: OperationsProject[] }) {
  const [selectedId, setSelectedId] = useState(projects[0]?.id ?? ""); const [pending, startTransition] = useTransition();
  const project = projects.find(item => item.id === selectedId) ?? projects[0]; const completion = taskCompletion(project?.tasks);
  function submitProgress(form: HTMLFormElement) { const data = new FormData(form); startTransition(async () => { try { await submitProgressUpdateAction(data); toast.success("Progress update published."); form.reset(); } catch(error) { toast.error(error instanceof Error ? error.message : "Failed to publish update."); } }); }
  function setTaskStatus(taskId: string, status: string) { startTransition(async () => { try { await updateOperationsTaskStatusAction(taskId, status); toast.success("Task status updated."); } catch(error) { toast.error(error instanceof Error ? error.message : "Failed to update task."); } }); }
  return <div className="min-h-screen bg-white p-0 sm:p-6"><header className="rounded-none bg-[linear-gradient(135deg,#112e1a,#1f6a37,#245f34)] p-5 text-white sm:rounded-2xl sm:p-6"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-white/65">Engineer Workspace</p><div className="mt-2 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-semibold">Field Progress</h1><p className="mt-2 max-w-xl text-sm text-white/75">Report actual site progress, surface blockers early, and keep CEO decisions grounded in field evidence.</p></div><select value={selectedId} onChange={e => setSelectedId(e.target.value)} className="h-11 min-w-64 rounded-lg border border-white/20 bg-white px-3 text-sm font-semibold text-apple-charcoal">{projects.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></div></header>
    {!project ? <div className="mt-5 rounded-2xl border border-dashed border-apple-mist p-14 text-center"><HardHat className="mx-auto text-emerald-700" /><h2 className="mt-3 text-xl font-semibold">No assigned projects</h2><p className="mt-2 text-sm text-apple-steel">A CEO must assign you as lead engineer or task owner.</p></div> : <div className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1fr)_410px]">
      <section className="min-w-0 space-y-5"><div className="grid gap-3 sm:grid-cols-3">{[["Reported progress", `${project.reported_progress}%`], ["Task completion", `${completion.completed}/${completion.total}`], ["Target date", formatOperationsDate(project.target_date)]].map(([label,value]) => <div key={label} className="rounded-xl border border-apple-mist p-4"><p className="text-xs text-apple-steel">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></div>)}</div>
        <div className="rounded-xl border border-apple-mist"><div className="flex items-center justify-between border-b border-apple-mist p-4"><div><h2 className="font-semibold">Assigned Site Tasks</h2><p className="text-xs text-apple-steel">{project.name} · {project.site}</p></div><ClipboardList className="text-emerald-700" size={20}/></div><div className="divide-y divide-apple-mist">{project.tasks?.map(task => <div key={task.id} className="flex flex-wrap items-center justify-between gap-3 p-4"><div><p className="text-sm font-semibold">{task.title}</p><p className="mt-1 text-xs text-apple-steel">Due {formatOperationsDate(task.due_date)}</p></div><select value={task.status} disabled={pending} onChange={e=>setTaskStatus(task.id,e.target.value)} className="h-9 rounded-lg border border-apple-mist px-3 text-xs font-semibold"><option value="todo">To do</option><option value="in_progress">In progress</option><option value="blocked">Blocked</option><option value="completed">Completed</option></select></div>)}{!project.tasks?.length && <p className="p-8 text-center text-sm text-apple-steel">No tasks assigned yet.</p>}</div></div>
        <div className="rounded-xl border border-apple-mist"><div className="border-b border-apple-mist p-4"><h2 className="font-semibold">Update history</h2><p className="text-xs text-apple-steel">Immutable chronological field reports</p></div><div className="divide-y divide-apple-mist">{[...(project.updates ?? [])].sort((a,b)=>b.created_at.localeCompare(a.created_at)).map(update => <article key={update.id} className="p-4"><div className="flex justify-between"><p className="font-semibold text-emerald-800">{update.progress_percent}% reported</p><p className="text-xs text-apple-steel">{formatOperationsDate(update.created_at)}</p></div><p className="mt-2 text-sm text-apple-smoke">{update.completed_work}</p>{update.blockers && <p className="mt-2 flex items-center gap-2 text-xs font-semibold text-rose-600"><AlertTriangle size={14}/>{update.blockers}</p>}{update.comments?.map(comment => <p key={comment.id} className="mt-3 rounded-lg bg-emerald-50 p-3 text-xs"><b>CEO:</b> {comment.body}</p>)}</article>)}{!project.updates?.length && <p className="p-8 text-center text-sm text-apple-steel">Your first report will appear here.</p>}</div></div>
      </section>
      <aside><form onSubmit={e => { e.preventDefault(); submitProgress(e.currentTarget); }} className="sticky top-6 rounded-xl border border-apple-mist p-5 shadow-[0_12px_28px_rgba(24,83,43,0.08)]"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-emerald-50 text-emerald-700"><Send size={18}/></span><div><h2 className="font-semibold">Publish progress update</h2><p className="text-xs text-apple-steel">Visible to the CEO immediately</p></div></div><input type="hidden" name="projectId" value={project.id}/><label className="mt-5 block text-sm font-semibold">Overall progress: engineer estimate</label><div className="mt-2 flex items-center gap-3"><input name="progressPercent" type="range" min="0" max="100" defaultValue={project.reported_progress} className="w-full accent-emerald-700"/><input name="progressDisplay" readOnly value={`${project.reported_progress}%`} className="h-10 w-16 rounded-lg border border-apple-mist text-center text-sm font-semibold"/></div><label className="mt-4 block text-sm font-semibold">Work completed</label><textarea name="completedWork" required rows={4} placeholder="What was completed since the last update?" className="mt-2 w-full rounded-lg border border-apple-mist p-3 text-sm"/><label className="mt-4 block text-sm font-semibold">Next steps</label><textarea name="nextSteps" required rows={3} placeholder="What will the team do next?" className="mt-2 w-full rounded-lg border border-apple-mist p-3 text-sm"/><label className="mt-4 block text-sm font-semibold">Blockers</label><textarea name="blockers" rows={2} placeholder="Delays, missing materials, decisions needed…" className="mt-2 w-full rounded-lg border border-apple-mist p-3 text-sm"/><label className="mt-4 flex cursor-pointer items-center gap-3 rounded-lg border border-dashed border-apple-silver bg-emerald-50/40 p-4 text-sm font-semibold text-emerald-800"><Camera size={18}/><span>Add site photos <small className="block font-normal text-apple-steel">JPG, PNG or WebP · max 10 MB each</small></span><input name="photos" type="file" accept="image/*" multiple className="sr-only"/></label><button disabled={pending} className="mt-5 flex h-11 w-full items-center justify-center gap-2 rounded-lg bg-[#087332] font-semibold text-white disabled:opacity-60">{pending ? "Publishing…" : <><CheckCircle2 size={17}/>Publish update</>}</button></form></aside>
    </div>}
  </div>;
}
